### ISSUE TITLE
investigate adding a visited set to the skeleton generator in sesame

### ISSUE THREAD

**Issue by tomsilver** [Learning-and-Intelligent-Systems/predicators#1117]
we're not 100% sure if anything would break, but I expect that in some cases, planning would get faster

**Comment by ronuchit** [comment]
turns out this doesn't work on stick_button and coffee (they both get around 25/50 with oracle), the reason is related to the general fact that predicates are a lossy abstraction for the purposes of bilevel planning, so in general we _don't_ want a visited set for skeleton generator in sesame

specifically, in stick_button:
* the predicates can't distinguish whether a button is reachable by the stick or by the robot
* and so a correct sequence of presses would end up with the same atoms as an incorrect sequence of presses
* for example, `press 0, pick stick, press 1, press 2, press 3` versus `press 1, pick stick, press 0, press 2, press 3`. if only the second one is correct, we'll never try it, because after `press 2` the atoms are the same as in the first skeleton
