### ISSUE TITLE
add `oracle` option for `sampler_learner`

### ISSUE THREAD

**Issue by tomsilver** [Learning-and-Intelligent-Systems/predicators#246]
when `do_sampler_learning` is False, we use uniformly random samplers (and so would expect this to do badly in many cases) when `do_option_learning` is False, we use _oracle_ options (and so would expect this to be as good as possible). this is confusing; let's rename one of them. @ronuchit what's your preference?

**Comment by ashayathalye** [comment]
relatedly, it might be nice to have something in the pipeline to make it easy to use oracle / ground truth samplers. Right now I am just hardcoding them into `nsrt_learning.py` for my specific use case.

**Comment by ronuchit** [comment]
@tomsilver Here's my preference for this. Like we do for some other settings, we should consolidate `do_option_learning` and `option_learner` into one flag named the latter, with choices `{"no_learning", "oracle"}`. And then we can do the same with `sampler_learner` having choices `{"neural", "random", "oracle"}`. The last one would be something new as per @ashayathalye's request. However, note that it's not as simple as it might seen initially: if you are learning the symbolic operators but you want to use oracle samplers, then that's only going to work if all your symbolic operators exactly match up with some oarcle operator, so that you can use that oracle operator's sampler. We'll need to throw an error otherwise.

**Comment by tomsilver** [comment]
sounds good to me. thanks!

**Comment by ronuchit** [comment]
first half of this is addressed by #250
