### ISSUE TITLE
Baseline: GNN policy that doesn't use predicates

### ISSUE THREAD

**Issue by tomsilver** [Learning-and-Intelligent-Systems/predicators#735]

**Comment by ronuchit** [comment]
After digging into this, I'm pretty sure we were already doing this the whole time. If you look in "run_predicators_main_experiments.sh" you'll see that for the GNN approach, we use the `--excluded_predicates all` flag, because we didn't want to be giving the GNN predicates that our system didn't have either!

So, you can control whether the GNN policy is given (non-goal) predicates by choosing whether or not to do `--excluded_predicates all`. I think we can close this PR?

I'm going to launch 160 experiments to test the GNN: {shooting, no shooting} x {exclude predicates, don't} x 4 envs x 10 seeds.

cc @tomsilver

**Comment by tomsilver** [comment]
yeah but I thought we want to exclude the goal predicates for the new baseline? @ronuchit

**Comment by ronuchit** [comment]
ehh why would we want to do that? that's weird anyway because then we can't be goal-conditioned, and so i think it might even be an ill-posed learning problem?

**Comment by tomsilver** [comment]
okay good point. we can close this then when you're done with your experiment!

**Comment by ronuchit** [comment]
will close it now, and add on results somewhere later
