### ISSUE TITLE
investigate backchaining with stick button environment

### ISSUE THREAD

**Issue by tomsilver** [Learning-and-Intelligent-Systems/predicators#863]
`python src/main.py --env stick_button --approach nsrt_learning --seed 0 --strips_learner backchaining`

**Comment by NishanthJKumar** [comment]
**Interesting finding**:

After printing out a bunch of plans, I'm starting to realize that the planner creates a bunch of redundant skeletons given the learned operators vs. the oracle operators. In particular, redundant skeletons are when the agent tries to press the same button twice. Somehow, the oracle hardly ever tries skeletons like this, but after learning operators with backchaining, even though there are fewer operators, the planner does this a lot.

My current prevailing hunch is that since stick point is really not downward-refinable given the predicates, the heuristic really influences how good search is. And somehow, our learned operators interact with the heuristic in a not-so-good way, even though the branching factor for task search is the same given the oracle vs. our operators. So from an `exp_nodes` POV, our operators are worse than the oracle, which something like `cluster_and_intersect()` would produce...

**Comment by ronuchit** [comment]
investigated further, it seems that skeletons like:
```
RobotPressButtonFromNothing [robby:robot, button0:button]
RobotPressButtonFromButton [robby:robot, button0:button, button0:button]
```
are getting heuristic values of inf in the non-sidelined operators, but non-inf in the sidelined operators

the reason is that with non-sidelined operators, RobotPressButtonFromButton has add effect `RobotAboveButton(?robot:robot, ?button:button)` and delete effect `RobotAboveButton(?robot:robot, ?from-button:button)`, so when the two buttons are the same, lmcut thinks we hit a dead end and reports inf. the difference with the sidelined operators is that while RobotPressButton also has add effect `RobotAboveButton(?robot:robot, ?button:button)`, it has a _side predicate_ `RobotAboveButton` rather than a delete effect; the side predicates are not seen by lmcut

closing because no further action required here.

cc @tomsilver @NishanthJKumar @wmcclinton
