### ISSUE TITLE
Ensure commands are deterministic for a given random seed. 

### ISSUE THREAD

**Issue by ashayathalye** [Learning-and-Intelligent-Systems/predicators#949]
If I run this command twice (so, the same random seed), I get two different results.
```python3 main.py --env doors --segmenter contacts --num_train_tasks 50 --timeout 300 --disable_harmlessness_check True --neural_gaus_regressor_max_itr 50000 --sampler_learner neural --approach nsrt_learning --option_learner direct_bc --num_test_tasks 50 --seed 0 --included_options MoveToDoor,MoveThroughDoor```.
(1) first time: 
```
Tasks solved: 15/ 50
Average time for successes: 4.87689 seconds
...
Main script terminated in 1594.71568 seconds
```
(2) second time: 
```
Tasks solved: 17 / 50
Average time for successes: 8.32305 seconds
...
Main script terminated in 2336.45988 seconds
```

I think given a random seed, we should be expecting determinism when the commands are run twice on the same computer. 

TODO: try running with fewer hyperparameters, and different environments.

**Comment by tomsilver** [comment]
@ashayathalye I reproduced this, and I'm noticing that in my case, there are a different number of demonstrations kept in the two runs, because a variable number of timeouts occur. note that counterintuitively, even though `--timeout 300`, we're still only allowing 10 seconds for planning with the oracle because `offline_data_planning_timeout` defaults to 10. possible courses of action:
* verify that the runs are deterministic if we increase `--offline_data_planning_timeout` enough to the point where all train tasks are solved by the oracle in demo collection
* if we feel like this is counterintuitive, we can talk about making `--offline_data_planning_timeout` default to `--timeout`. I would probably be in favor of this change.
